=== jacbeekers/metadata-registry-interface-specifications/metadata/schemas/interface/0.2.0/physical_attribute_association.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/jacbeekers/metadata-registry-interface-specifications/blob/master/metadata/schemas/interface/0.2.0/physical_attribute_assoc.json",
  "title": "Physical Entity Association",
  "description": "The association of two (or more) physical attributes",
  "required": [
    "meta",
    "meta_version",
    "uid",
    "name",
    "version",
    "physical_entity_association",
    "source_target_attribute_links"
  ],
  "type": "object",
  "properties": {
    "meta": {
      "type": "string",
      "description": "metadata type",
      "enum": [
        "physical_attribute_association"
      ]
    },
    "meta_version": {
      "type": "string",
      "description": "the meta structure version for the object",
      "pattern": "^([0-9]+).([0-9]+).*$"
    },
    "uid": {
      "description": "The unique identifier for the association",
      "type": "string",
      "format": "uuid"
    },
    "name": {
      "description": "The name of the association for later referral",
      "type": "string"
    },
    "version": {
      "description": "The version number of the association",
      "pattern": "^([0-9]+).([0-9]+).([0-9]+)$",
      "type": "string"
    },
    "physical_entity_association": {
      "oneOf": [
        {
          "type": "string",
          "format": "uuid",
          "pattern": "^(.+)-(.+)-(.+)$"
        }
      ],
      "description": "To which this attribute association belongs"
    },
    "source_target_attribute_links": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/source_target_attribute_link"
      },
      "uniqueItems": true
    }
  },
  "definitions": {
    "source_target_attribute_link": {
      "type": "object",
      "required": [
        "transformation"
      ],
      "properties": {
        "transformation": {
          "$ref": "#/definitions/transformation"
        },
        "description": {
          "type": "string",
          "description": "Explanation of the transformation"
        },
        "formula": {
          "type": "string",
          "description": "Formula applied to the attributes. Use the names or UUIDs of the attributes and place it in {{}}, e.g. '{{LastName}}' or '{{19aee165-025c-4358-97ed-08ba90910c47}}'"
        }
      }
    },
    "transformation": {
      "type": "object",
      "required": [
        "uid",
        "from",
        "to"
      ],
      "properties": {
        "uid": {
          "type": "string",
          "description": "The transformation id. Use the same id when multiple source attributes lead to the same target attribute"
        },
        "from": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "type": "string",
                "format": "uuid",
                "pattern": "^(.+)-(.+)-(.+)$"
              }
            ]
          },
          "description": "The source attributes (or existing references to it/them)"
        },
        "to": {
          "oneOf": [
            {
              "type": "string",
              "format": "uuid",
              "pattern": "^(.+)-(.+)-(.+)$"
            }
          ],
          "description": "The target attribute (or existing reference to it)"
        }
      }
    }
  }
}

=== jacbeekers/metadata-registry-interface-specifications/metadata/test_resources/0.2.0/correct_attribute_association_with_uuids.json
{
  "meta": "physical_attribute_association",
  "meta_version": "0.2.0",
  "uid": "bc6f6de3-9901-4007-976b-46ea66e9a699",
  "name": "attribute1 to attribute2",
  "version": "1.0.0",
  "physical_entity_association": "53ad44a7-66e9-4374-acf2-d02d8e233820",
  "source_target_attribute_links": [
    { "transformation" : {
      "uid" : "df439fcf-bd8a-4707-ab93-2aed47e4d28d",
      "from" : [ "d042b292-7c81-408a-ad43-49833ca804c1", "df439fcf-bd8a-4707-ab93-2aed47e4d28d" ],
      "to": "ed2359d8-9bc8-4fc8-bc6e-d4a2385efcc0",
      "description": "Fields are concatenated with a space character",
      "formula": "{{d042b292-7c81-408a-ad43-49833ca804c1}} + ' ' + {{df439fcf-bd8a-4707-ab93-2aed47e4d28d}}"
    }
    }
  ]
}
