=== jacbeekers/metadata-registry-interface-specifications/metadata/schemas/interface/0.2.0/physical_attribute_assoc.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://somewhere.jacbeekers.nl/metadata/schemas/interface/0.2.0/physical_attribute_assoc.json",
  "title": "Physical Entity Association",
  "description": "The association of two (or more) physical attributes",
  "required": [
    "uid",
    "name",
    "version",
    "physicalEntityAssocation",
    "sourceTargetAttributeLinks"
  ],
  "type": "object",
  "properties": {
    "meta": {
      "type": "string",
      "description": "metadata type",
      "enum": [
        "physical_attribute_assoc"
      ]
    },
    "uid": {
      "description": "The unique identifier for the association",
      "type": "string",
      "format": "uuid"
    },
    "name": {
      "description": "The name of the association for later referral",
      "type": "string"
    },
    "version": {
      "description": "The version number of the association",
      "pattern": "^([0-9]+).([0-9]+).([0-9]+)$",
      "type": "string"
    },
    "physicalEntityAssocation": {
      "oneOf": [
        {
          "$ref": "file:metadata-registry-interface-specifications/metadata/schemas/interface/0.2.0/physical_entity_assoc.json"
        },
        {
          "type": "string",
          "format": "uuid",
          "pattern": "^(.+)-(.+)-(.+)$"
        }
      ],
      "description": "To which this attribute association belongs"
    },
    "sourceTargetAttributeLinks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/sourceTargetAttributeLink"
      },
      "uniqueItems": true
    }
  },
  "definitions": {
    "sourceTargetAttributeLink": {
      "type": "object",
      "required": [
        "transformation"
      ],
      "properties": {
        "transformation": {
          "$ref": "#/definitions/transformation"
        },
        "description": {
          "type": "string",
          "description": "Explanation of the transformation"
        },
        "formula": {
          "type": "string",
          "description": "Formula applied to the attributes. Use the names or UUIDs of the attributes and place it in {{}}, e.g. '{{LastName}}' or '{{19aee165-025c-4358-97ed-08ba90910c47}}'"
        }
      }
    },
    "transformation": {
      "type": "object",
      "required": [
        "uid",
        "from",
        "to"
      ],
      "properties": {
        "uid": {
          "type": "string",
          "description": "The transformation id. Use the same id when multiple source attributes lead to the same target attribute"
        },
        "from": {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "file:metadata-registry-interface-specifications/metadata/schemas/interface/0.2.0/physical_attribute.json"
              },
              {
                "type": "string",
                "format": "uuid",
                "pattern": "^(.+)-(.+)-(.+)$"
              }
            ]
          },
          "description": "The source attributes (or existing references to it/them)"
        },
        "to": {
          "oneOf": [
            {
              "$ref": "file:metadata-registry-interface-specifications/metadata/schemas/interface/0.2.0/physical_attribute.json"
            },
            {
              "type": "string",
              "format": "uuid",
              "pattern": "^(.+)-(.+)-(.+)$"
            }
          ],
          "description": "The target attribute (or existing reference to it)"
        }
      }
    }
  }
}

=== jacbeekers/metadata-registry-interface-specifications/metadata/test_resources/0.1.0/correct_attribute_association_with_uuids.json
{
  "uid": "bc6f6de3-9901-4007-976b-46ea66e9a699",
  "name": "attribute1 to attribute2",
  "version": "1.0.0",
  "physicalEntityAssocation": "d042b292-7c81-408a-ad43-49833ca804c1",
  "sourceTargetAttributeLinks": [
    { "transformation" : {
      "uid" : "df439fcf-bd8a-4707-ab93-2aed47e4d28d",
      "from" : [ "d042b292-7c81-408a-ad43-49833ca804c1", "df439fcf-bd8a-4707-ab93-2aed47e4d28d" ],
      "to": "ed2359d8-9bc8-4fc8-bc6e-d4a2385efcc0",
      "description": "Fields are concatenated with a space character",
      "formula": "{{d042b292-7c81-408a-ad43-49833ca804c1}} + ' ' + {{df439fcf-bd8a-4707-ab93-2aed47e4d28d}}"
    }
    }
  ]
}
