=== jacbeekers/metadata-registry-interface-specifications/metadata/schemas/interface/0.1.0/physical_entity_assoc.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://somewhere.abnamro.com/metadata/schemas/interface/0.1.0/physical_entity_assoc.json",
  "title": "Physical Entity Association",
  "description": "The association of two (or more) physical entities",
  "required": [
    "uid",
    "name",
    "version",
    "job",
    "dag",
    "task"
  ],
  "type": "object",
  "properties": {
    "uid": {
      "description": "The unique identifier for the association",
      "type": "string",
      "format": "uuid"
    },
    "name": {
      "description": "The name of the association for later referral",
      "type": "string"
    },
    "job": {
      "oneOf": [
        {
          "$ref": "file:metadata/schemas/interface/0.1.0/job.json"
        },
        {
          "type": "string",
          "format": "uuid",
          "pattern": "^(.+)-(.+)-(.+)$"
        }
      ],
      "description": "The job that conducts the task"
    },
    "dag": {
      "oneOf": [
        {
          "$ref": "file:metadata/schemas/interface/0.1.0/dag.json"
        },
        {
          "type": "string",
          "format": "uuid",
          "pattern": "^(.+)-(.+)-(.+)$"
        }
      ],
      "description": "The DAG that schedules the data tasks"
    },
    "task": {
      "oneOf": [
        {
          "$ref": "file:metadata/schemas/interface/0.1.0/task.json"
        },
        {
          "type": "string",
          "format": "uuid",
          "pattern": "^(.+)-(.+)-(.+)$"
        }
      ],
      "description": "The task, as part of the job, that processes the data"
    },
    "version": {
      "description": "The version number of the association",
      "pattern": "^([0-9]+).([0-9]+).([0-9]+)$",
      "type": "string"
    },
    "sourceTargetEntityLinks": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/sourceTargetEntityLink"
      },
      "uniqueItems": true
    }
  },
  "definitions": {
    "sourceTargetEntityLink": {
      "type": "object",
      "required": [
        "from",
        "to"
      ],
      "properties": {
        "from": {
          "oneOf": [
            {
              "$ref": "file:metadata/schemas/interface/0.1.0/physical_entity.json"
            },
            {
              "type": "string",
              "format": "uuid",
              "pattern": "^(.+)-(.+)-(.+)$"
            }
          ]
        },
        "to": {
          "oneOf": [
            {
              "$ref": "file:metadata/schemas/interface/0.1.0/physical_entity.json"
            },
            {
              "type": "string",
              "format": "uuid",
              "pattern": "^(.+)-(.+)-(.+)$"
            }
          ]
        }
      }
    }
  }
}

=== jacbeekers/metadata-registry-interface-specifications/metadata/test_resources/correct_entity_association_with_uids.json
{
  "uid": "53ad44a7-66e9-4374-acf2-d02d8e233820",
  "name": "entity1 to entity2",
  "job": "2c43088b-0ae3-411f-bb0f-f33e40b21f9c",
  "dag": "24231a7a-acd0-4f5d-86a6-77fa61028c1a",
  "task": "dddf8c61-24f3-420b-8be8-8edcc834c7a4",
  "version": "1.0.0",
  "sourceTargetEntityLinks": [ { "from" : "d042b292-7c81-408a-ad43-49833ca804c1", "to": "ed2359d8-9bc8-4fc8-bc6e-d4a2385efcc0"}]
}
