=== jacbeekers/metadata-registry-interface-specifications/metadata/schemas/interface/0.3.0/physical_attribute.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/jacbeekers/metadata-registry-interface-specifications/blob/master/metadata/schemas/interface/0.2.0/physical_attribute.json",
  "title": "Physical Attribute",
  "description": "Description of the physical attribute",
  "required": [
    "meta",
    "meta_version",
    "attribute_list",
    "physical_entity",
    "version"
  ],
  "type": "object",
  "properties": {
    "meta": {
      "type": "string",
      "description": "metadata type",
      "enum": [
        "physical_attribute"
      ]
    },
    "meta_version": {
      "type": "string",
      "description": "the meta structure version for the object",
      "pattern": "^([0-9]+).([0-9]+).*$"
    },
    "attribute_list": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/attribute"
      },
      "uniqueItems": true
    },
    "physical_entity": {
      "oneOf": [
        {
          "type": "string",
          "format": "uuid",
          "pattern": "^(.+)-(.+)-(.+)$"
        }
      ],
      "description": "Physical entity the attribute belongs to. In this version only uuids, references to existing physical entities, are allowed."
    },
    "version": {
      "description": "The metadata version number of the attribute list. Increase whenever something changes.",
      "pattern": "^([0-9]+).([0-9]+).([0-9]+)$",
      "type": "string"
    }
  },
  "definitions": {
    "attribute": {
      "type": "object",
      "required": [
        "uid",
        "name"
      ],
      "properties": {
        "uid": {
          "description": "The unique identifier of the physical attribute.",
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "description": "The name of the physical attribute.",
          "type": "string"
        },
        "description": {
          "description": "The description of the physical attribute.",
          "type": "string"
        },
        "datatype": {
          "description": "The data type of the physical attribute.",
          "type": "string"
        }
      }
    }
  }
}

=== jacbeekers/metadata-registry-interface-specifications/tests/resources/0.2.0/correct_attribute_source.json
{
  "meta": "physical_attribute",
  "meta_version": "0.2.0",
  "version": "1.0.0",
  "attribute_list": [
    {
      "uid": "f6299c11-1a24-4b3f-9cf5-20e3a91f5933",
      "name": "source_field_1",
      "description": "The attribute is 1"
    },
    {
      "uid": "f6299c11-1a24-4b3f-9cf5-dffaffasf",
      "name": "source_field_2",
      "description": "The attribute is 2"
    },
    {
      "uid": "d042b292-7c81-408a-ad43-49833ca804c1",
      "name": "source_field_3"
    },
    {
      "uid": "df439fcf-bd8a-4707-ab93-2aed47e4d28d",
      "name": "source_field_4"
    }
  ],
  "physical_entity" : "d042b292-7c81-408a-ad43-49833ca804c1"
}

=== jacbeekers/metadata-registry-interface-specifications/metadata/test_resources/0.2.0/correct_attribute_target.json
{
  "meta": "physical_attribute",
  "meta_version": "0.2.0",
  "version": "1.0.0",
  "attribute_list": [
    {
      "uid": "ed2359d8-9bc8-4fc8-bc6e-d4a2385efcc0",
      "name": "out_attribute_1",
      "description": "The attribute is 1"
    },
    {
      "uid": "ae91794d-dde0-4412-a7ba-1be0025d4480",
      "name": "out_attribute_2",
      "description": "The attribute is 2"
    }
  ],
  "physical_entity" : "399dfd85-b109-4ac0-b38e-1702844e24e5"
}

=== jacbeekers/metadata-registry-interface-specifications/metadata/test_resources/0.2.0/correct_attribute_with_uuid.json
{
  "meta": "physical_attribute",
  "meta_version": "0.2.0",
  "version": "1.0.0",
  "attribute_list": [
    {
      "uid": "f6299c11-1a24-4b3f-9cf5-20e3a91f5933",
      "name": "attribute 1",
      "description": "The attribute is 1"
    },
    {
      "uid": "f6299c11-1a24-4b3f-9cf5-dffaffasf",
      "name": "attribute 2",
      "description": "The attribute is 2"
    }
  ],
  "physical_entity" : "d042b292-7c81-408a-ad43-49833ca804c1"
}
